spring.application.name=InterviewX

server.port=${PORT:8080}

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA (Changed to update to prevent data loss on restarts)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Google OAuth
google.client-id=${GOOGLE_CLIENT_ID}

# Upload
file.upload-dir=uploads
resume.upload-dir=uploads/resume

# Mail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Gemini
gemini.api.key=${GEMINI_API_KEY}

# RapidAPI
rapidapi.key=${RAPIDAPI_KEY}
rapidapi.host=jsearch.p.rapidapi.com
rapidapi.url=https://jsearch.p.rapidapi.com/search-v2

# Redis (Comment these out if you don't have a Redis service active yet)
spring.data.redis.host=${REDIS_HOST}
spring.data.redis.port=${REDIS_PORT}

spring.cache.type=none
spring.cache.redis.time-to-live=3600000
spring.cache.redis.cache-null-values=false

logging.level.org.springframework.security=DEBUG

server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=always